frame = "buttonless"
title-hidden = true
fork = true
idle = true
maximized = false
no-multigrid = false
srgb = true
tabs = true
theme = "auto"
vsync = true

[font]
size = 13

[[font.normal]]
family = "JetBrainsMono Nerd Font"
style = "Normal"

[[font.bold]]
family = "JetBrainsMono Nerd Font"
style = "SemiBold"

[[font.italic]]
family = "Maple Mono"
style = "Italic"

[[font.bold_italic]]
family = "Maple Mono"
style = "SemiBold Italic"

[box-drawing]
# "font-glyph", "native" or "selected-native"
mode = "native"
# selected = "î‚¹ğŸ®ğŸ®‘ğŸ®’î¸€î¸î¸‚î¸ƒî¸„î¸…"
